### ISSUE TITLE
Cannot respect CRUD arch. Impossible to implement 'delete' route.

### ISSUE THREAD

**Issue by kilianp07** [kilianp07/TrainWebBack#6]
Impossible to implement 'delete' route because that's impossible to implement it without deleting it from the database. Add a status attribute to each Sequelize Model to resolve it.

**Comment by Ninotter** [comment]
https://github.com/kilianp07/TrainWebBack/commit/3b8d6f382286a6ca0bd060c7cd69e78f9081120f
